# Render.com configuration
services:
  - type: web
    name: chatbot-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chatbot-db
          property: connectionString
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: OPENROUTER_API_KEY
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080

databases:
  - name: chatbot-db
    databaseName: chatbot
    user: chatbot
