# Render.com configuration
services:
  - type: web
    name: chatbot-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/chatbot-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chatbot-db
          property: connectionString
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: OPENROUTER_API_KEY
        sync: false
      - key: JAVA_TOOL_OPTIONS
        value: "-Xmx512m"

databases:
  - name: chatbot-db
    databaseName: chatbot
    user: chatbot

